### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Xelbayria** [cahyawibawa/posterpy#1]
Hello, 

There are two things you should be aware of: 
- IMDbPY is no long being maintained, it's been renamed as cinemagoer (
- What version of python is used to run PosterPy (Python 3.11 no longer support `Pillow v9.0.0`)

It would be nice to know which version making it easier to avoid any problems. 

Also I ran the script and got an error: 
```
Traceback (most recent call last):
  File "...\PosterPy\post.py", line 102, in <module>
    URL = 'https://api.themoviedb.org/3/find/tt{0}?api_key={1}&language=en-US&external_source=imdb_id'.format(search_movie(), api_key())
  File "...PosterPy\post.py", line 72, in search_movie
    p = ("{: <10}".format(str(get_id))+ get_title + " " + "(" + str(get_year) + ")")
UnboundLocalError: local variable 'get_year' referenced before assignment
```
If u know what's wrong with this, then please advise. Thanks for taking your time to read.

**Comment by cahyawibawa** [comment]
> Hello,
> 
> There are two things you should be aware of:
> 
> * IMDbPY is no long being maintained, it's been renamed as cinemagoer (
> * What version of python is used to run PosterPy (Python 3.11 no longer support `Pillow v9.0.0`)
> 
> It would be nice to know which version making it easier to avoid any problems.
> 
> Also I ran the script and got an error:
> 
> ```
> Traceback (most recent call last):
>   File "...\PosterPy\post.py", line 102, in <module>
>     URL = 'https://api.themoviedb.org/3/find/tt{0}?api_key={1}&language=en-US&external_source=imdb_id'.format(search_movie(), api_key())
>   File "...PosterPy\post.py", line 72, in search_movie
>     p = ("{: <10}".format(str(get_id))+ get_title + " " + "(" + str(get_year) + ")")
> UnboundLocalError: local variable 'get_year' referenced before assignment
> ```
> 
> If u know what's wrong with this, then please advise. Thanks for taking your time to read.

hello thanks for telling, i have fixed it 👌
i am using python v 3.11.1 if you encounter problem again try to reinstall again in requirement.txt file i have updated it

**Comment by Xelbayria** [comment]
Thanks for getting back to me. 

there is one thing I noticed in `requirement.txt`  it has a bit of typo   `request` are supposed to be `requests` with "s"

and how do you run `requirements.txt`??? originally, they don't have `pip install` and had `package_name==version`

**Comment by cahyawibawa** [comment]
thanks mates for correcting me, yes in my case just change imdbpy to cinemagoer and it runs normally

**Comment by Xelbayria** [comment]
> thanks mates for correcting me, yes in my case just change imdbpy to cinemagoer and it runs normally

That's interesting, it run normally. 

the problem is this `def search_movie()`: 
```
        ia = Cinemagoer()
        user_input = input("Search for a movie: ")
        print("\n", end="")
        movies = ia.search_movie(user_input)

        choices_list = []

        for i in movies:
            get_title = i['title']
            get_id = i.movieID
            try:
                get_year = i['year']       <- Right here won't get the value we need. 
            except KeyError:
                pass
            p = ("{: <10}".format(str(get_id))+ get_title + " " + "(" + str(get_year) + ")")
            choices_list.append(p)
```

As you can see `i['year']` is not getting the value for "year", I've looked at the documentation, it said using `ia.search_movie("movie name")` will have less data, so the only data that it contains "title", that's it. 

So I changed it to `get_year = ia.get_movie(get_id)['year']`  and it fixed my problem (the error above). Anyway, I'll close this issue as solved. 

Have a good day! Thanks for answering a few questions. I recommend that you add which version of python are used to run the PosterPy.
